[build]
    base = ".next/"
    command = "npm run build && npm run export"
    publish = "/"


[[plugins]]
  package = "@netlify/plugin-nextjs"


[[redirects]]
from = "/*"
to = "/index.html"
status = 200